name: Update PR Templates
on:
  workflow_dispatch:
    inputs:
      repo-type:
        required: true
        type: choice
        description: Repo Type
        options:
          - terraform
          - chef
      
jobs:
  pr-template-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update PR Templates
        run: | 
          git submodule add https://github.com/tahsib-optimizely/pr-templates.git pr-templates
          cd pr-templates
          chmod +x ./sync.sh
          bash ./sync.sh ${{ inputs.repo-type }}

      - name: Clean Up Submodule
        run: |
          chmod +x ./pr-templates/cleanup.sh
          bash ./pr-templates/cleanup.sh
        
      - name: Push to new-pr-template branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: pr-templates-updated
          branch: new-pr-templates
          create_branch: true
          push_options: --force