name: Update PR Templates
on:
  pull_request:
    branches:
      - main

jobs:
  pr-template-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update PR Templates
        run: | 
          git submodule add https://github.com/tahsib-optimizely/pr-templates.git pr-templates
          cp -rf ./pr-templates/* .github/PULL_REQUEST_TEMPLATE/
          
      - name: Cleanup submodule
        run: |
          echo "**** Cleaning up submodules ****"
          git submodule deinit -f -- pr-templates    
          git rm --cached pr-templates    
          rm -rf .git/modules/pr-templates
          rm -f .gitmodules
          rm -rf pr-templates
          echo "**** Cleaning Complete! ****"
        
      - name: Push to new-pr-template branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: pr-templates-updated
          branch: new-pr-templates
          create_branch: true
          push_options: --force