name: Update Common Files
on:
  workflow_dispatch:
    inputs:
      repo-type:
        required: true
        description: Repo Type
        default: 'terraform'
      pre-commit-config:
        description: 'Name of the pre-commit-config file for your repository'
        
      
jobs:
  update-common-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: optimizely/sre-metadata-github-action@main
        with:
          repository-type: ${{ inputs.repo-type }}
          github-token: ${{ secrets.TEST_ACTION }}
          pre-commit-config: ${{ inputs.pre-commit-config }}