name: Update PR Templates
on:
  workflow_dispatch:
    inputs:
      repo-type:
        required: true
        description: Repo Type
        default: 'terraform'
        
      
jobs:
  pr-template-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: tahsib-optimizely/pr-templates@main
        with:
          repo-type: ${{ inputs.repo-type }}

