name: Update Common Files
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      repo-type:
        required: true
        description: Repository Type
        default: 'terraform'
      pre-commit-config:
        default: 'default'
        
        
        
      
jobs:
  update-common-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: tahsib-optimizely/sre-metadata-github-action@main
        with:
          repository-type: ${{ inputs.repo-type || 'terraform' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pre-commit-config: ${{ inputs.pre-commit-config || 'default'}}